### ISSUE TITLE
slurmctld exited with code 1

### ISSUE THREAD

**Issue by vipints** [giovtorres/slurm-docker-cluster#10]
Thanks for the package. I have tried to start up the service but get the error message from `slurmdbd` and `slurmctld`

```
slurmctld    | ---> Starting the MUNGE Authentication service (munged) ...
slurmctld    | munged: Error: Failed to check keyfile "/etc/munge/munge.key": No such file or directory
```

The build process didn't give me any error message. Any idea what is wrong here?

**Comment by giovtorres** [comment]
Still facing this issue? Perhaps creating the munge key didn't work, or an issue with the volume? Closing for now. Please feel free to respond or reopen the issue. Thanks.
