### ISSUE TITLE
Update to SLURM and Centos stable version

### ISSUE THREAD

**Issue by pablohe** [giovtorres/slurm-docker-cluster#16]
Hi!

Will be nice have Centos 8 and slurm 20.11

**Comment by giovtorres** [comment]
PR #21 aims to replace CentOS 7 with RockyLinux 8. Would that be ok, or are you explicitly looking for CentOS 8?

You can always change the version of slurm by using build args. See the build instructions in the README. PR #21 also aims to make the versioning a little more dynamic.
