### ISSUE TITLE
/usr/sbin/slurmdbd: error while loading shared libraries: libslurmfull.so

### ISSUE THREAD

**Issue by wl-freedom** [giovtorres/slurm-docker-cluster#25]
I built 21.08.6、21.08.4
When start slurmctld, slurmdbd, mysql, and slurm through docker compose，slurmdbd will report an error，The error is as follows：
/usr/sbin/slurmdbd: error while loading shared libraries: libslurmfull.so: cannot open shared object file: No such file or directory

But I can find it in the docker container。
Even if I set LD_ LIBRARY_ PATH in the container  will still report this problem。
I don't know what to do

**Comment by wl-freedom** [comment]
I've found the reason，/usr/lib64/slurm directory has no permission, need to give the slurm user permission.
because "exec gosu slurm /usr/sbin/slurmdbd -Dvvv" in docker-entrypoint.sh

**Comment by giovtorres** [comment]
Hmm, everything under `/usr/lib64` is typically world-readable. This is what I see inside the container as the `slurm` user, with all files being world-readable, as expected:

```
[slurm@67f65538d86f /]$ ls /usr/lib64/slurm/ -ld
drwxr-xr-x. 3 root root 12288 Dec 28 16:38 /usr/lib64/slurm/
```

```
[slurm@67f65538d86f /]$ ls /usr/lib64/slurm/ -l
total 279008
-rw-r--r--. 1 root root 13746600 Dec 28 16:36 accounting_storage_mysql.a
-rwxr-xr-x. 1 root root     1090 Dec 28 16:36 accounting_storage_mysql.la
-rwxr-xr-x. 1 root root  2456144 Dec 28 16:36 accounting_storage_mysql.so
[...]
```
