### ISSUE TITLE
mysql upgrade to mariadb?

### ISSUE THREAD

**Issue by lcrownover** [giovtorres/slurm-docker-cluster#26]
Looks like mysql:5.7 container doesn't work with arm processors (m1 mac).

```
[+] Running 0/1
 ⠸ mysql Pulling                                                                               1.3s
no matching manifest for linux/arm64/v8 in the manifest list entries
```

Replacing `image: mysql:5.7` with `image: mariadb:10.10` seems to correct the issue. I am able to exec into the cluster and run a simple job. I have not done much testing beyond that.

I'd hate to fork this repo just for that small change. Any chance someone would be willing to take a look?

**Comment by giovtorres** [comment]
Thanks for pointing this out. Would you feel ok submitting a PR for this change?

**Comment by lcrownover** [comment]
Sure, opened #28
