### ISSUE TITLE
`docker-compose build` command line in `README.md` is incorrect.

### ISSUE THREAD

**Issue by stevenjswanson** [giovtorres/slurm-docker-cluster#27]
You have 

```
SLURM_TAG=slurm-19-05-2-1 IMAGE_TAG=19.05.2 docker-compose build
```

But I think you need to use `--build-arg` to set those variable so they are used by `Dockerfile`

**Comment by giovtorres** [comment]
You would use `--build-arg` when using the `docker` CLI. However, when using `docker-compose`, prefixing the command with these environment variables passes it into the `docker-compose.yml` file [here](https://github.com/giovtorres/slurm-docker-cluster/blob/master/docker-compose.yml#L21), for example. The `docker-compose.yml` file has defaults which you can override at runtime.

**Comment by giovtorres** [comment]
The Dockerfile can [interpolate](https://docs.docker.com/reference/compose-file/interpolation/) variables from the environment.

Closing.
