### ISSUE TITLE
Why not add user login node into this slurm cluster?

### ISSUE THREAD

**Issue by zengqingfu1442** [giovtorres/slurm-docker-cluster#30]

**Comment by giovtorres** [comment]
You could easily add one to the Dockerfile. This project was meant more for testing and development. A login node assumes users. You could maintain an environment using this cluster for users, but it doesn't replace a real cluster as it does not have all the features. Would love to know your use case. 

I'm closing this for now. Feel free to respond. Thanks!

**Comment by whophil** [comment]
FYI, [this branch](https://github.com/whophil/slurm-docker-cluster/tree/feature/login) implements a simple login node by extending the original docker image (adds `openssh-server`) and by adding a `login` entrypoint which runs `munge` and `ssdh`.
