### ISSUE TITLE
slurm container can't start

### ISSUE THREAD

**Issue by fang19911030** [giovtorres/slurm-docker-cluster#32]
My host machine is Windows.  I can't use _docker compose up_ to start dockers, the errors are:

- slurmdbd   | exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
- slurmctld  | exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
- c2         | exec /usr/local/bin/docker-entrypoint.sh: no such file or directory
- c1         | exec /usr/local/bin/docker-entrypoint.sh: no such file or directory

I don't understand why this file is not exist, I think the image build process does not have any issues.

**Comment by giovtorres** [comment]
Sorry, I don't have a Windows environment to test on. That file is certainly in the container:

```
[root@slurmctld /]# ls -l /usr/local/bin/docker-entrypoint.sh
-rwxr-xr-x 1 root root 1716 Dec 28  2022 /usr/local/bin/docker-entrypoint.sh
```

Could be something with how it is running on Windows. I'll close for now, but if you have solved this, please feel free to respond with the fix here for future reference. Thanks!
