### ISSUE TITLE
uptime command not found

### ISSUE THREAD

**Issue by recap** [giovtorres/slurm-docker-cluster#37]
The README.md suggests submitting a test job with command uptime. procps-ng package is not installed but also uptime in docker containers does not really work since it reports host uptime. So maybe some other command is more suitable like hostname which will give you the host on which the job landed.

**Comment by giovtorres** [comment]
would you mind submitting a PR?

**Comment by recap** [comment]
sure here: https://github.com/giovtorres/slurm-docker-cluster/pull/38

**Comment by giovtorres** [comment]
Closed by #38
