### ISSUE TITLE
slurmdb: slurm_acct_db.linux_job_table' doesn't exist

### ISSUE THREAD

**Issue by roksys** [giovtorres/slurm-docker-cluster#9]
Hey,

Thanks for an amzing job you did dockerizing Slurm!

I would like to ask if you are aware of an issue with `slurmdbd`?

```
slurmdbd: debug2: DBD_JOB_START: START CALL ID:4 NAME:wrap INX:0
slurmdbd: debug2: as_mysql_job_start: called
slurmdbd: error: We should have gotten a new id: Table 'slurm_acct_db.linux_job_table' doesn't exist
slurmdbd: error: It looks like the storage has gone away trying to reconnect
slurmdbd: error: We should have gotten a new id: Table 'slurm_acct_db.linux_job_table' doesn't exist
```

Is it the reason why `sacct` output is empty?

```
[root@slurmctld /]# sacct
sacct     sacctmgr  
[root@slurmctld /]# sacct
       JobID    JobName  Partition    Account  AllocCPUS      State ExitCode 
------------ ---------- ---------- ---------- ---------- ---------- -------- 
```

**Comment by giovtorres** [comment]
Hi @roksys, I believe I inadvertently removed the instruction from the README that says to register the cluster. I've put it back: https://github.com/giovtorres/slurm-docker-cluster#register-the-cluster-with-slurmdbd

Could you run this script to register the cluster? This should make sure `sacct` outputs meaningful information about jobs.
